context:
  version: "0.87.0"

package:
  name: metro
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/metro/-/metro-${{ version }}.tgz
  sha256: 051893de1c3da3c476827ac5b8f11c9e653b81b0f5fae59aebadcc8ebb9509e4

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - metro --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The JavaScript bundler for React Native
  homepage: https://github.com/facebook/metro
  repository: https://github.com/facebook/metro

extra:
  recipe-maintainers:
    - danielnachun
