context:
  version: "0.86.0"

package:
  name: metro
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/metro/-/metro-${{ version }}.tgz
  sha256: 42a7358964d91df3166e13c04ea685448a028b1fa839aab75bcacb88aafa186e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - metro --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The JavaScript bundler for React Native
  homepage: https://github.com/facebook/metro
  repository: https://github.com/facebook/metro

extra:
  recipe-maintainers:
    - danielnachun
