context:
  version: "0.82.0"

package:
  name: metro
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/metro/-/metro-${{ version }}.tgz
  sha256: 8a93cd11250a0ccd309d5ea252d7882f8de70c539ad1308bea39c25f7960d138

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - metro --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The JavaScript bundler for React Native
  homepage: https://github.com/facebook/metro
  repository: https://github.com/facebook/metro

extra:
  recipe-maintainers:
    - danielnachun
