context:
  version: "0.84.3"

package:
  name: metro
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/metro/-/metro-${{ version }}.tgz
  sha256: ba1baf54870c5caa9c05319c592e15b5ee9d8881b2b33d8bea9ccdab14837928

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - metro --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The JavaScript bundler for React Native
  homepage: https://github.com/facebook/metro
  repository: https://github.com/facebook/metro

extra:
  recipe-maintainers:
    - danielnachun
