context:
  version: "0.82.3"

package:
  name: metro
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/metro/-/metro-${{ version }}.tgz
  sha256: ba15fd57d5e6b079277fee01e2883b505f2bc01fabbfe24021c7dabef2879606

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - metro --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The JavaScript bundler for React Native
  homepage: https://github.com/facebook/metro
  repository: https://github.com/facebook/metro

extra:
  recipe-maintainers:
    - danielnachun
